### PR TITLE
Remove deprecated export functions

### PR DESCRIPTION
**Pull request by Elad-Laufer**
ToImage() always passes through PNG as it is guaranteed to be supported and lossless

### CODE REVIEW

**Comment by tonimelisma** [comment]
Is this backwards compatible?

**Comment by Elad-Laufer** [comment]
> Is this backwards compatible?

No. I've removed exported functions.

**Comment by davidbyttow** [comment]
Thanks @Elad-Laufer !

**Comment by tonimelisma** [comment]
Hey @davidbyttow are you sure we want to break backwards compatibility? Or does this mean we should bump up the major version number?

**Comment by davidbyttow** [comment]
Hey @tonimelisma to be honest I didn’t give this too much deep thought. My thinking is that people should be pinning to a specific version, but then again I know that’s not the reality. Perhaps we should revert this and then bump the major (or minor since this has been deprecated for a while now) and then roll forward. Though if we are going to bump the major version then I would like to see if there are other changes to fold in. 

WDYT @tonimelisma @Elad-Laufer ?

**Comment by tonimelisma** [comment]
I've tried to follow Go's [backwards compatibility policy](https://go.dev/blog/module-compatibility) pretty strictly. So basically bump up the major version for breaking changes.

I've tried to think about other changes we would want to do simultaneously with a version bump. I wonder where are with regards to supporting all libvips importing and exporting parameters? Would there be breaking changes there we could implement simultaneously?

Might this also be a good time to refactor the export parameters to an alternative that's easier for both us as well as govips users? With the struct we use there's the challenge that we can't see when a user overrides any specific parameters on the govips side. For users, it's a bit more complicated to always get a struct from ``NewDefaultJPEGExportParams()``, fill it in and then pass it back, instead of a simpler variadic interface (such as e.g. [here](https://pkg.go.dev/github.com/disintegration/imaging#Open)). Not sure if such a change would be worth the effort.

**Comment by davidbyttow** [comment]
Good points, will consider though, but generally agree on the refactor. I need to get my head back into this for a day to form an opinion.

**Comment by tonimelisma** [comment]
Sure. Apologies for the lack of availability on my end recently and for the coming weeks, I'm just relocating to SF with my family and there's a lot on my table.

**Pull request merged**
