### PR TITLE
Added support for OpenSlide formats.

### PR DESCRIPTION
**Pull request by freedombird9**
libvips support OpenSlide formats by default. The current binding initiates vips images only from buffer.  OpenSlide images cannot be loaded this way. I added several new APIs specifically to load OpenSlide images and images of any other formats that libvips possibly supports.

### CODE REVIEW

**Comment by tonimelisma** [comment]
@freedombird9 thanks for the PR! Unfortunately govips maintenance was on a bit of a pause although we're now getting back up to speed. I fully realise it's been over a year since you raised the PR - is it still relevant and should we work to get it to merge to the latest or should I just close the PR?

**Comment by freedombird9** [comment]
@tonimelisma Well I don't have a preference since it's been so long and I've finished working on my project with my forked govip.  I think the feature is still nice to have though.

**Comment by tonimelisma** [comment]
Ok, thanks for the info. Considering there's no immediately demand I won't prioritise it for now.

**Comment by jonasteuwen** [comment]
Hi, I would still think openslide is a relevant feature. Could we add this feature?

**Comment by tonimelisma** [comment]
Hey @jonasteuwen sure, if you'll provide an up to date PR that passes all the tests I'll review and merge it

**Pull request closed without merging**
