### PR TITLE
implement divide

### PR DESCRIPTION
**Pull request by axkirillov**

### CODE REVIEW

**Comment by axkirillov** [comment]
My divide test is failing but its not on my machine, while other tests, like multiply fail on my machine. If I delete golden image for multiply and generate a new one, the test passes on my machine. So this is probably an issue with my setup, and the golden image I produce on my mac doest pass in the build.

**Comment by axkirillov** [comment]
@tonimelisma any ideas on why could that be?

**Comment by tonimelisma** [comment]
@axkirillov that's likely due to a weird version of libvips or something similar. Please submit the PR without including the golden picture in the resources folder.

**Comment by axkirillov** [comment]
@axkirillov i just did brew reinstall vips and I still produce wrong images, here you can see that color is different
image

**Comment by axkirillov** [comment]
@tonimelisma I deleted the image and now it passes

**Comment by tonimelisma** [comment]
Generally looks great. The relative test coverage on the total shows it's decreasing a little bit, is it possible that you fix that?

**Pull request merged**
