### PR TITLE
AVIF support

### PR DESCRIPTION
**Pull request by Andrewsville**
As promised in #186, here is my attempt at supporting AVIF :)

Pretty much everything is a copy paste from HEIF support with a couple of differences:

* The `isHeif` function was returning TRUE for AVIF as well and this should stay, since HEIF is the container for both HEIC and AVIF. On top of that there is a new `isAvif` function.
* AVIF is exported by the `heifsave` function in libvips. That's why the `ImageTypes` map contains `heif` for AVIF.
* libvips docs say the default quality value is 50 but `NewHeifExportParams` is setting 80, so I used 80.
* In `foreign.c` when loading a heif image, it gets autorotated. Honestly, I have no idea if it should be done for AVIFs too :)

There are also two very basic tests.

So it should be more or less working :) Please take a look and I'll be happy to fix any bug you may find.

### CODE REVIEW

**Comment by tonimelisma** [comment]
Hey @Andrewsville and thanks for the PR - looks great. The automated testing is failing on Ubuntu 20.04 for some reason. Could you check the output of the CI and debug?

**Comment by Andrewsville** [comment]
Interesting, tooks like the 20.04 libvips-dev doesn't know heif or something like that. I have the same issue when I try to run the tests locally in a Docker image. I'll investigate it.

**Comment by tonimelisma** [comment]
Hey @Andrewsville did you get any clarity on this?

**Comment by Andrewsville** [comment]
Sorry for the late reply. I finally had the time to investigate and the reason is quite simple. The `ppa:tonimelisma/ppa` repo does not contain libheif for 20.04 meaning the distribution will be used. And its older but more importantly not compiled against libaom so ti doesn't support AVIF.

It have tried to add the PPA repo from libheif authors that contains versions for both 18.04 and 20.04 with all dependencies. Their more modern version requires a newer libde265 than in the distribution, so I have added their PPA of libde265, too.

Let's see if it helped :)

**Comment by Andrewsville** [comment]
And it looks like the golden tests fail with newer deps, especially libheif. Apart from golden tests, everything passes. Could you publish a libheif package for 20.04?

**Pull request merged**
