### PR TITLE
support fail_on level

### PR DESCRIPTION
**Pull request by jishi92**
libvips support a variety of fail levels by fail_on.
This can fix  [issue](https://github.com/davidbyttow/govips/issues/319).

### CODE REVIEW

**Comment by tonimelisma** [comment]
Hey @jishi92 I'd be very supportive of this change. However, tests aren't passing.

**Comment by jishi92** [comment]
Hi @tonimelisma , it build failed with 
`Error: vips/foreign.go:125:32: could not determine kind of name for C.VIPS_FAIL_ON_ERROR
Error: vips/foreign.go:123:32: could not determine kind of name for C.VIPS_FAIL_ON_NONE
Error: vips/foreign.go:124:[32](https://github.com/davidbyttow/govips/actions/runs/3337904810/jobs/5524856597#step:7:33): could not determine kind of name for C.VIPS_FAIL_ON_TRUNCATED
Error: vips/foreign.go:126:32: could not determine kind of name for C.VIPS_FAIL_ON_WARNING
Error: Process completed with exit code 2.`

However,the VipsFailOn level is exist including C.VIPS_FAIL_ON_ERROR and  C.VIPS_FAIL_ON_NONE...

See it (https://www.libvips.org/API/current/VipsForeignSave.html#VipsFailOn).

What's the version of libvips using in build shell?

**Comment by tonimelisma** [comment]
Hey @jishi92, you can find that out from the CI/CD details. We need to be background compatible, so although I love the idea of the PR, at a minimum we would need to validate the libvips version before utilizing any cutting edge functionality.

**Comment by jishi92** [comment]
Hey @tonimelisma , I change the failOn enum to int. Now build/tests passed on linux. The tests on Mac are failed and it looks like a history problem having nothing to do with this change.

**Pull request closed without merging**
