### PR TITLE
vips_embed implements extend background with color parameter

### PR DESCRIPTION
**Pull request by cshum**
Re-create the pull request from https://github.com/davidbyttow/govips/pull/234

vips_embed implement extend background with color parameter:

https://www.libvips.org/API/current/libvips-conversion.html#vips-embed

https://www.libvips.org/API/current/libvips-conversion.html#VIPS-EXTEND-BACKGROUND:CAPS

### CODE REVIEW

**Comment by davidbyttow** [comment]
LGTM, is this ready to be merged @cshum ?

**Comment by davidbyttow** [comment]
Also, if you want to re-integrate with this (rather than your fork) for your Imagor project, I am happy to make you a collaborator

**Comment by cshum** [comment]
Hi @davidbyttow this is ready to be merged. The only reason I am using my fork is because of the additional changes being used. I would very keen to be a collaborator.

**Comment by davidbyttow** [comment]
OK, for now can you rebase this with my latest commit? It fixes the tests.

**Pull request merged**
