### PR TITLE
Cast

### PR DESCRIPTION
**Pull request by axkirillov**
this PR implements a public method for vips_cast

### CODE REVIEW

**Review by davidbyttow — APPROVED** [review]

**Comment by davidbyttow** [comment]
@tonimelisma any idea why this one test is faililng? And here: https://github.com/davidbyttow/govips/pull/162

(I haven't looked in detail yet)

**Comment by davidbyttow** [comment]
Can probably ignore this failing test, just need to fix separately

**Comment by tonimelisma** [comment]
@davidbyttow new vips version 8.10.5 being pulled from homebrew for macOS 11.0. I'll update the golden reference images later today or if you have macOS 11.0 you can do it yourself as well. The thing is the golden test go file needs to be edited as macOS reference images are shared among all macOS version so we'd need to add the version tag to the files (like there is on the linux files)

**Comment by davidbyttow** [comment]
Makes sense @tonimelisma: https://github.com/davidbyttow/govips/pull/163

I don't have 10.* available and so can't update golden files there

**Comment by davidbyttow** [comment]
true

**Comment by davidbyttow** [comment]
@tonimelisma should we just merge this one too?

**Comment by tonimelisma** [comment]
Great minds think alike 👍

**Pull request merged**
