### PR TITLE
Fixes TIFF compression for #21

### PR DESCRIPTION
**Pull request by davidbyttow**

### CODE REVIEW

**Review by tonimelisma — COMMENTED** [review]
Not sure how much difference it makes but the Go examples have a specific format, they're built as part of testing etc. [Testable Examples](https://blog.golang.org/examples) shows the package to be ```package_test```

**Comment by davidbyttow** [comment]
> Not sure how much difference it makes but the Go examples have a specific format, they're built as part of testing etc. [Testable Examples](https://blog.golang.org/examples) shows the package to be `package_test`

Yeah, I re-added it back.

Also, how did you generate the golden files for the other platforms?

**Comment by davidbyttow** [comment]
Also, do these qualify as examples? These just seem like example programs with main functions (not Example tests)

**Comment by tonimelisma** [comment]
I've got a bunch of docker images with different Ubuntu versions. I'll build the golden images.

I guess we can keep them in examples if we want to, although we could put them in tests as benchmarks as well which have their own format (not the JS one though).

One question: should we also create a NewDefaultTIFFExportParams() function to create default values for these new parameters or is NewDefaultExportParams() sufficient?

We should also probably work to finish the PR about the import parameters.

Otherwise looks good to me, I can merge after adding the golden.

**Comment by davidbyttow** [comment]
I think NewDefaultExportParams is sufficient for now. However, I also think we will want to move toward format-specific export types. I haven't given too much thought yet on how to do that, but I like how Sharp has explicit output functions that allow you to pass in all of the format-specific options. We should offer the same flexibility.

**Pull request merged**
