### PR TITLE
add ExtractBandToImage

### PR DESCRIPTION
**Pull request by roffe**
Function will allow extracting band(s) into a new image not overwriting the original image reference

### CODE REVIEW

**Comment by roffe** [comment]
I found myself having to do `img2 := img.Copy() -> img2.ExtractBand` to get alpha channel out

**Comment by tonimelisma** [comment]
Hey @roffe. Thank you very much for the contribution! Did you check out the contribution document? Would you mind writing unit tests, passing and failing ones?

**Review by tonimelisma — APPROVED** [review]
lgtm

**Comment by roffe** [comment]
thank you very much

**Pull request merged**
