### PR TITLE
WIP: allow image load options

### PR DESCRIPTION
**Pull request by victorkt**
This is a work in progress to add the ability of passing additional parameters to libvips loader functions, as mentioned on issue #23 . It also adds the options for other image types as well. It should already work, still pending the tests which I'll add later.

Please let me know your thoughts and what could be improved or changed.

---
This change is [Reviewable](https://reviewable.io/reviews/davidbyttow/govips/26)

### CODE REVIEW

**Comment by davidbyttow** [comment]
Thanks! Will take a look

**Comment by tonimelisma** [comment]
Hey @victorkt! The PR looks great and I'd be cautiously optimistic about including this in govips. Unfortunately I understand it's been quite some time since your PR, and due to a large amount of new functionality it no longer merges. Is this still relevant to you and would you like us to work on getting it to merge, or should I just close the PR?

**Comment by victorkt** [comment]
Hi @tonimelisma, I'm not working on that project anymore and I wouldn't have time to update this PR unfortunately. Feel free to close it.

**Comment by tonimelisma** [comment]
Ok @victorkt thank you for the contribution in any case. I'll take a look at merging it manually later!

**Pull request closed without merging**
