### PR TITLE
[WiP] Add VipsSourceCustom using go callbacks and an io.Reader

### PR DESCRIPTION
**Pull request by vansante**
Still needs some work.

### CODE REVIEW

**Comment by tonimelisma** [comment]
Thanks for this @vansante. Is it possible you explain a little bit about the objectives and benefits of the PR and the high-level architectural description how you are looking to implement this?

**Comment by vansante** [comment]
@tonimelisma Yes, the idea is to make the reading of image truly streaming by using the new [libvips streaming api](https://libvips.github.io/libvips/2019/12/11/What's-new-in-8.9.html). So then there will be a technical difference between opening an image using `NewImageFromReader` which utilizes an `io.Reader` to load the image data directly into vips and using `NewImageFromBuffer` which loads a binary blob into memory and then passes that to vips (currently they do the same thing, except `NewImageFromReader` uses `ioutil.ReadAll` to get the data). 

The idea is to also introduce the streaming output `VipsTargetCustom` in a subsequent MR so you can use vips fully via its streaming api.

Let me know if this is a desired change before I proceed :)

**Comment by tonimelisma** [comment]
Sounds good to me - this would be an exciting upgrade!

I'm wondering what all the implications to the core functionality will be. Will all core processing methods need to be upgraded? Will the core processing methods automatically detect whether they're working with a buffer or stream?

@davidbyttow @Elad-Laufer  what are your thoughts? Do you see any issues or do you have guidance how to implement this?

Thank you @vansante for being an active contributor!

**Comment by zzjin** [comment]
Great work!
I've made some benchmarks witch shows maybe there was not enough difference:

bench test code:
```go
var testFile = resources + "jpg-24bit.jpg"
var testFunc = func(img *ImageRef) {
	img.Thumbnail(100, 100, InterestingCentre)
}

func BenchmarkLoadFromFile(b *testing.B) {
	benchHelper(b, testFile, NewImageFromFile, testFunc)
}
func BenchmarkLoadFromSource(b *testing.B) {
	benchHelper(b, testFile, func(file string) (*ImageRef, error) {
		// Test with using an image source
		imageFile, _ := os.Open(file)
		return NewImageFromReader(imageFile)
	}, testFunc)
}
```

witch output is:
```
goos: linux
goarch: amd64
pkg: github.com/davidbyttow/govips/v2/vips
BenchmarkLoadFromFile-8     	     339	   3502284 ns/op	    3956 B/op	      29 allocs/op
BenchmarkLoadFromSource-8   	     276	   3798112 ns/op	    2685 B/op	      47 allocs/op
```
test with thumbnail func, which is most common usage.

PS: libvips mem shows:
```
file: Mem: 30320640, MemHigh: 30374736, Files: 0, Allocs: 5040
```

```
source: Mem: 33569280, MemHigh: 33623376, Files: 0, Allocs: 5580
```

**Comment by sethify** [comment]
This is exciting. Is this PR still active?

**Comment by tonimelisma** [comment]
Hey @vansante! This PR still looks awesome. Do you see any technical or architectural issues blocking progress? Do you feel like you could allocate time for this in the coming weeks?

**Comment by vansante** [comment]
I was not really sure if this was still something to be desired after zzjin mentioned that the benchmarks are not showing improvements so I had not looked at it anymore since then. I should probably do some benchmarking of my own (possibly with the writers streaming as well). I think I can take a look at it again in the next 2 weeks.

**Comment by tonimelisma** [comment]
Hmm. I think the original issue where the benchmark was raised related to throughput speed, which the benchmark is actually not measuring. Govips is used in several backend services where streaming support might provide big end-to-end throughput benefits, I'm all for it.

**Comment by vansante** [comment]
I had a look at the current MR and I identified the following issues:

- All images loaded through the streaming `VipsSourceCustom` loader seem to lose metadata (EXIF and stuff), and thus most of the Golden image tests fail.
- I made the `free()` function on the `Source` struct, but its never called. I just tried creating a third callback for `close` but that doesnt work. I am not quite sure when it is safe to garbage collect the C `GoSourceArguments` struct and remove the `Source` from the map in Go.
- I would rather have a direct pointer in C-land in the `GoSourceArguments` struct rather than keeping and manager a global map with associated lock in Go. This would make the setup much more elegant.

If anyone has any good ideas for these issues, please let me know! :)

**Comment by tonimelisma** [comment]
Apologies, but I'm doing some cleanup and closing this PR due to lack of activity. I still think the streaming API would be a great improvement but unfortunately don't have great ideas how to architect this change. Thanks for the contribution in any case!

**Comment by negator** [comment]
@vansante Have you considered using the [Pipe function](https://pkg.go.dev/os#Pipe), which returns a pair of files for reading/writing? You can access the underlying file descriptors to create VipsSource and VipsTarget objects (using [vips-source-new-from-descriptor](https://www.libvips.org/API/current/VipsTargetCustom.html#vips-source-new-from-descriptor) and [vips-target-new-to-descriptor](https://www.libvips.org/API/current/VipsTargetCustom.html#vips-target-new-to-descriptor)), and forgo the need for `GoSourceArguments` and the global map entirely.

**Comment by vansante** [comment]
Hi @negator,

To be honest I haven't looked (much) at the (go)vips code since my last comment, and I am not sure whether I will have time to look at this again soon. Your suggestion sounds very promising however, so feel free to take over from me!

**Pull request closed without merging**
