### PR TITLE
Add interpolator parameter to mapim

### PR DESCRIPTION
**Pull request by axkirillov**
this pull request addds an interpolator parameter to mapim

### CODE REVIEW

**Comment by axkirillov** [comment]
I dont have an ubuntu installation to check this, but it seems like calling vips_interpolate_new with nickname "nearest" was producing a nil reference
I added a fallback to bilinear to prevent this, but perhaps this is not too good, because it obscures whats happening to the caller
not sure what would be correct solution here, which accounts for this error but also does not break the mapim test

**Comment by tonimelisma** [comment]
Hey @axkirillov thanks again for the great contribution.

My quick takeaways:
- As interpolator is an enum, should you perhaps specify the type for lines 93-98 as `Interpolator`? Can you also rename the constants (e.g. Nearest should be InterpolatorNearest) so it's clear what the constants refer to?
- As these are exported types and constants, can you also add documentation comments? See logging.go lines 9-21 as an example
- I don't think lines 66-69 in resample.go are healthy. vipsMapim() is a private function which is only called via *ImageRef.Mapim() which should take care of defining the interpolator. Please add error handling logging to Mapim() and/or to vipsInterpolateNew() to ensure the interpolator is successfully initialised and usable before calling vipsMapim().

You've got the GitHub CI that has both Ubuntu 18.04 as well as 20.04, you can keep testing your commits on both of them even if you don't have Ubuntu yourself. I don't understand the errors coming from the tests right now and don't feel comfortable merging this PR. Apologies but we've had some quality issues before where I've haphazardly accepted a PR without ensuring it's bug free.

I'd really appreciate you check where the SIGSEGV is actually coming from and why before merging this PR.

Apologies if some of my comments are ignorant, perhaps I didn't fully understand the flow of the new parameters. And thanks again for the contribution!

On the stack trace suppose you're talking about this error in the CI test run: https://github.com/davidbyttow/govips/runs/1871000564

```
=== RUN   TestImageRef_Mapim
1986
2021/02/10 11:59:51 [govips.info] warning libvips already started
1987
fatal error: unexpected signal during runtime execution
1988
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ff2fad94134]
1989

1990
runtime stack:
1991
runtime.throw(0x6cce42, 0x2a)
1992
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/panic.go:1116 +0x72
1993
runtime.sigpanic()
1994
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/signal_unix.go:726 +0x4ac
1995

1996
goroutine 209 [syscall]:
1997
runtime.cgocall(0x644340, 0xc000045e50, 0xc0002cc090)
1998
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/cgocall.go:133 +0x5b fp=0xc000045e20 sp=0xc000045de8 pc=0x40a43b
1999
github.com/davidbyttow/govips/v2/vips._Cfunc_mapim(0x7ff2942dfaf0, 0xc0002cc090, 0x7ff2b81b1000, 0x0, 0xc000000000)
2000
	_cgo_gotypes.go:1242 +0x4d fp=0xc000045e50 sp=0xc000045e20 pc=0x62b46d
2001
github.com/davidbyttow/govips/v2/vips.vipsMapim.func1(0x7ff2942dfaf0, 0xc0002cc090, 0x7ff2b81b1000, 0x0, 0x7ff2b818b990)
2002
	/home/runner/work/govips/govips/vips/resample.go:66 +0xe7 fp=0xc000045e88 sp=0xc000045e50 pc=0x640da7
2003
github.com/davidbyttow/govips/v2/vips.vipsMapim(0x7ff2942dfaf0, 0x7ff2b81b1000, 0x0, 0x0, 0x0, 0x1)
2004
	/home/runner/work/govips/govips/vips/resample.go:66 +0x85 fp=0xc000045ed8 sp=0xc000045e88 pc=0x639525
2005
github.com/davidbyttow/govips/v2/vips.(*ImageRef).Mapim(0xc000012240, 0xc000012340, 0x6bcf2b, 0x7, 0x0, 0x0)
2006
	/home/runner/work/govips/govips/vips/image.go:591 +0x65 fp=0xc000045f18 sp=0xc000045ed8 pc=0x635505
2007
github.com/davidbyttow/govips/v2/vips.TestImageRef_Mapim(0xc00012ed80)
2008
	/home/runner/work/govips/govips/vips/image_test.go:491 +0x188 fp=0xc000045f80 sp=0xc000045f18 pc=0x6264e8
2009
testing.tRunner(0xc00012ed80, 0x6d7e38)
2010
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1123 +0xef fp=0xc000045fd0 sp=0xc000045f80 pc=0x4fdb4f
2011
runtime.goexit()
2012
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000045fd8 sp=0xc000045fd0 pc=0x475381
2013
created by testing.(*T).Run
2014
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1168 +0x2b3
2015

2016
goroutine 1 [chan receive]:
2017
testing.(*T).Run(0xc00012ed80, 0x6c374d, 0x12, 0x6d7e38, 0x496201)
2018
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1169 +0x2da
2019
testing.runTests.func1(0xc000001980)
2020
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1439 +0x78
2021
testing.tRunner(0xc000001980, 0xc0000bdd38)
2022
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1123 +0xef
2023
testing.runTests(0xc00000e620, 0x87a0e0, 0x81, 0x81, 0xc00111160b4289b5, 0x8bb2d52ec9, 0x938000, 0xc0000bddf0)
2024
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1437 +0x2fe
2025
testing.(*M).Run(0xc0000c4180, 0x0)
2026
	/opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1345 +0x1eb
2027
github.com/davidbyttow/govips/v2/vips.TestMain(0xc0000c4180)
2028
	/home/runner/work/govips/govips/vips/image_test.go:18 +0x2b
2029
main.main()
2030
	_testmain.go:389 +0x1f6
2031

2032
goroutine 25 [select]:
2033
github.com/davidbyttow/govips/v2/vips.collectStats.func1(0xc0000212d8, 0xc000068780)
2034
	/home/runner/work/govips/govips/vips/stats.go:28 +0xd9
2035
created by github.com/davidbyttow/govips/v2/vips.collectStats
2036
	/home/runner/work/govips/govips/vips/stats.go:26 +0xbd
```

I truly hate going through CGo stack traces. I ran the same commit on my Ubuntu Groovy. Trying to interpret my stack trace it says it's:
- Calling the method `*ImageRef.Mapim(0xc0000a22c0, 0xc0000a2300, 0x6b9e0b, 0x7, 0x0, 0x0)` - as I understand it, methods' first parameter is the associated type and the second parameter in the stack trace is the first parameter in Go (also an ImageRef in this case) while the third parameter is the interpolator string. Not sure why we have three more parameters here?
- Calling the private function `vipsMapim(0x105a1b0, 0x7fbbf070f980, 0x0, 0x0, 0x0, 0x1)` - here the first two parameters are the ImageRefs but the interpolator string seems null here?
- Calling another private function `vipsMapim.func1(0x105a1b0, 0xc00009e120, 0x7fbbf070f980, 0x0, 0x7fbc0c054c40)` - I don't understand func1() here, what's happening and why is it calling it?
- Calling the CGo function `_Cfunc_mapim(0x105a1b0, 0xc00009e120, 0x7fbbf070f980, 0x0, 0xc000000000)`

**Comment by axkirillov** [comment]
@tonimelisma Thank you for detailed comments. I will look into this, when I have some time. Ofc, I don't want to merge unstable code.

**Comment by tonimelisma** [comment]
Hey @axkirillov I'm closing this PR for now due to lack of activity. If at any time you have the time to finish it, all contributions are greatly appreciated!

**Pull request closed without merging**
