### PR TITLE
Toni

### PR DESCRIPTION
**Pull request by tonimelisma**
Fixed the URLs. This should be mergeable. There's still a lot of fixes to get this to build which I'll submit separately.

### CODE REVIEW

**Review by davidbyttow — APPROVED** [review]
Thanks!

**Comment by davidbyttow** [comment]
This definitely changes the API, we'll need to bump the major version

**Comment by tonimelisma** [comment]
So do you want to accept it so I can start pushing more stuff, or..?

**Comment by davidbyttow** [comment]
Let's be iterative. Can you merge?

**Pull request merged**
